#!/usr/bin/python2
# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------
# CDraft, a fork of PyRoom.
# Copyright (c) 2007 Nicolas P. Rougier & NoWhereMan
# Copyright (c) 2008 The Pyroom Team - See AUTHORS file for more information
# Copyright (c) 2011 Matthew Bunday
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------

"""
CDraft - A fork of PyRoom
=============================

:copyright: 2007 Nicolas P. Rougier & NoWhereMan Copyright
:copyright: 2008 The PyRoom Theme - See AUTHORS file for more information
:copyright: 2011 Matthew Bunday
:license: GNU General Public License, version 3 or later
"""

import sys, CDraft.cmdline

try:
    sys.exit(CDraft.cmdline.main())
except KeyboardInterrupt:
    sys.exit(1)
