.TH CDraft 1 "11 Mar 2011"
.SH NAME
\fBCDraft\fP \- crafty and drafty writing

.SH DESCRIPTION
.fi
.B CDraft
lets you edit text files simply and efficiently in a full-screen window, with no distractions.
.nf
.LP
.SH OPTIONS

.TP
\fB\-\-help\fR
Prints the command line options and exits..
.TP
\fB\-\-version\fR
Prints the programm's version and exits.
.TP
\fBfilename(s)...\fR
Specifies the file to open
.SH BUGS
If you find a bug, please report it at 

.B https://github.com/SlyShy/CDraft
.SH AUTHORS
Matthew Bunday
